Opnames = [
    # --- Data Movement & Constants ---
    "MOVE",
    "ENCRYPTED_LOAD_CONST",
    "LOAD_CONST",
    "LOAD_NONE",
    "LOAD_FAST",
    # --- Scoping & Variables ---
    "GET_BUILTIN",
    "SET_BUILTIN",
    "STORE_GLOBAL",
    "STORE_GLOBAL",
    "GET_UPVAL",
    "SET_UPVAL",
    # --- Data Structures & Attributes ---
    "BINARY_SUBSCR",
    "STORE_SUBSCR",
    "LOAD_ATTR",
    "STORE_ATTR",
    "BUILD_LIST",
    "BUILD_MAP",
    "LOAD_METHOD",
    "SET_LIST",
    "BUILD_STRING",
    "MAKE_CLASS",
    # --- Arithmetic & Unary ---
    "BINARY_ADD",
    "BINARY_SUB",
    "BINARY_MUL",
    "BINARY_DIV",
    "BINARY_MOD",
    "BINARY_POW",
    "BINARY_OR",
    "BINARY_XOR",
    "BINARY_AND",
    "BINARY_RSHIFT",
    "BINARY_LSHIFT",
    "BINARY_FLOORDIV",
    "UNARY_ADD",
    "UNARY_SUB",
    "UNARY_INV",
    "UNARY_NOT",
    "GET_LEN",
    "FORMAT_VALUE",
    # --- Control Flow & Comparison ---
    "JUMP",
    "JUMP_IF_FALSE",
    "JUMP_IF_TRUE",
    "COMPARE_EQ",
    "COMPARE_NE",
    "COMPARE_LT",
    "COMPARE_LTE",
    "COMPARE_GT",
    "COMPARE_GTE",
    "COMPARE_IS",
    "COMPARE_ISNOT",
    "COMPARE_IN",
    "COMPARE_NOTIN",
    "GET_ITER",
    "FOR_ITER",
    # --- Exception Handling ---
    "SETUP_FINALLY",
    "SETUP_EXCEPT",
    "EXCEPT_MATCH",
    "STORE_EXCEPTION_AS",
    "POP_BLOCK",
    "POP_EXCEPT",
    "RAISE_EXCEPTION",
    "END_FINALLY",
    # --- Function Calls & Returns ---
    "CALL",
    "CALL_KW",
    "RETURN_VALUE",
    "ASSERT",
    # --- Closures & Scoping ---
    "MAKE_FUNCTION",
    "BUILD_SLICE",
    "LOAD_CLOSURE",
    "VARARG",
    # --- Imports ---
    "IMPORT_NAME",
    "IMPORT_FROM",
    "IMPORT_STAR",
]